"""Built-in connector catalog for HBN.

Copyright (C) 2026 Luis Mauricio Junqueira Zanin
Licensed under the GNU Affero General Public License v3.0 or later.
"""

from __future__ import annotations

from typing import Any, Dict, List


def built_in_connectors() -> List[Dict[str, Any]]:
    """Return first-party connector descriptors known to the current runtime."""
    return [
        {
            "connector_id": "hbn.connector.runtime.codex",
            "kind": "runtime",
            "display_name": "Codex Runtime Adapter",
            "runtime_family": "gpt",
            "surface_runtimes": ["codex"],
            "supported_human_languages": ["*"],
            "supported_target_technologies": ["*"],
            "translator_impl_language": "python",
            "delivery_languages": ["markdown", "shell"],
            "coupling_modes": ["bootstrap_wrapper", "runtime_adapter"],
            "installation_mode": "bootstrap_or_adapter",
            "source": {
                "type": "local_builtin",
                "locator": "src/usehbn/runtime.py",
                "trust_level": "approved",
            },
            "requires_human_approval": False,
        },
        {
            "connector_id": "hbn.connector.runtime.claude-code",
            "kind": "runtime",
            "display_name": "Claude Code Runtime Adapter",
            "runtime_family": "claude",
            "surface_runtimes": ["claude-code"],
            "supported_human_languages": ["*"],
            "supported_target_technologies": ["*"],
            "translator_impl_language": "python",
            "delivery_languages": ["markdown"],
            "coupling_modes": ["runtime_adapter"],
            "installation_mode": "adapter",
            "source": {
                "type": "local_builtin",
                "locator": "src/usehbn/runtime.py",
                "trust_level": "approved",
            },
            "requires_human_approval": False,
        },
        {
            "connector_id": "hbn.connector.runtime.cursor",
            "kind": "runtime",
            "display_name": "Cursor Runtime Adapter",
            "runtime_family": "cursor",
            "surface_runtimes": ["cursor"],
            "supported_human_languages": ["*"],
            "supported_target_technologies": ["*"],
            "translator_impl_language": "python",
            "delivery_languages": ["mdc", "markdown"],
            "coupling_modes": ["runtime_adapter"],
            "installation_mode": "adapter",
            "source": {
                "type": "local_builtin",
                "locator": "src/usehbn/runtime.py",
                "trust_level": "approved",
            },
            "requires_human_approval": False,
        },
        {
            "connector_id": "hbn.connector.runtime.copilot",
            "kind": "runtime",
            "display_name": "Copilot Runtime Adapter",
            "runtime_family": "copilot",
            "surface_runtimes": ["copilot"],
            "supported_human_languages": ["*"],
            "supported_target_technologies": ["*"],
            "translator_impl_language": "python",
            "delivery_languages": ["markdown"],
            "coupling_modes": ["runtime_adapter"],
            "installation_mode": "adapter",
            "source": {
                "type": "local_builtin",
                "locator": "src/usehbn/runtime.py",
                "trust_level": "approved",
            },
            "requires_human_approval": False,
        },
        {
            "connector_id": "hbn.connector.runtime.chatgpt",
            "kind": "runtime",
            "display_name": "ChatGPT Runtime Adapter",
            "runtime_family": "gpt",
            "surface_runtimes": ["chatgpt"],
            "supported_human_languages": ["*"],
            "supported_target_technologies": ["*"],
            "translator_impl_language": "python",
            "delivery_languages": ["markdown"],
            "coupling_modes": ["runtime_adapter"],
            "installation_mode": "adapter",
            "source": {
                "type": "local_builtin",
                "locator": "src/usehbn/runtime.py",
                "trust_level": "approved",
            },
            "requires_human_approval": False,
        },
        {
            "connector_id": "hbn.connector.runtime.gemini",
            "kind": "runtime",
            "display_name": "Gemini Runtime Adapter",
            "runtime_family": "gemini",
            "surface_runtimes": ["gemini"],
            "supported_human_languages": ["*"],
            "supported_target_technologies": ["*"],
            "translator_impl_language": "python",
            "delivery_languages": ["markdown"],
            "coupling_modes": ["runtime_adapter"],
            "installation_mode": "adapter",
            "source": {
                "type": "local_builtin",
                "locator": "src/usehbn/runtime.py",
                "trust_level": "approved",
            },
            "requires_human_approval": False,
        },
        {
            "connector_id": "hbn.connector.runtime.antigravity",
            "kind": "runtime",
            "display_name": "Antigravity Runtime Adapter",
            "runtime_family": "antigravity",
            "surface_runtimes": ["antigravity"],
            "supported_human_languages": ["*"],
            "supported_target_technologies": ["*"],
            "translator_impl_language": "python",
            "delivery_languages": ["markdown"],
            "coupling_modes": ["runtime_adapter"],
            "installation_mode": "adapter",
            "source": {
                "type": "local_builtin",
                "locator": "src/usehbn/runtime.py",
                "trust_level": "approved",
            },
            "requires_human_approval": False,
        },
        {
            "connector_id": "hbn.connector.legacy.vba",
            "kind": "legacy_bridge",
            "display_name": "Excel/VBA Legacy Bridge",
            "runtime_family": "bridge",
            "surface_runtimes": ["legacy_bridge"],
            "supported_human_languages": ["*"],
            "supported_target_technologies": ["excel-vba", "access-vba"],
            "translator_impl_language": "python",
            "delivery_languages": ["vba", "bas", "cls", "frm", "markdown"],
            "coupling_modes": ["embedded_target_code", "documentary_bridge"],
            "installation_mode": "manual_or_builtin",
            "source": {
                "type": "local_builtin",
                "locator": "src/usehbn/bridge/vba.py",
                "trust_level": "approved",
            },
            "requires_human_approval": True,
        },
        {
            "connector_id": "hbn.connector.bridge.python",
            "kind": "language_bridge",
            "display_name": "Python Bridge",
            "runtime_family": "bridge",
            "surface_runtimes": ["legacy_bridge", "shell"],
            "supported_human_languages": ["*"],
            "supported_target_technologies": ["python"],
            "translator_impl_language": "python",
            "delivery_languages": ["python", "markdown"],
            "coupling_modes": ["embedded_target_code", "documentary_bridge"],
            "installation_mode": "manual_or_builtin",
            "source": {
                "type": "local_builtin",
                "locator": "src/usehbn/connectors/catalog.py",
                "trust_level": "approved",
            },
            "requires_human_approval": True,
        },
        {
            "connector_id": "hbn.connector.bridge.java",
            "kind": "language_bridge",
            "display_name": "Java Bridge",
            "runtime_family": "bridge",
            "surface_runtimes": ["legacy_bridge", "shell"],
            "supported_human_languages": ["*"],
            "supported_target_technologies": ["java"],
            "translator_impl_language": "python",
            "delivery_languages": ["java", "markdown"],
            "coupling_modes": ["embedded_target_code", "documentary_bridge"],
            "installation_mode": "manual_or_builtin",
            "source": {
                "type": "local_builtin",
                "locator": "src/usehbn/connectors/catalog.py",
                "trust_level": "approved",
            },
            "requires_human_approval": True,
        },
        {
            "connector_id": "hbn.connector.bridge.cpp",
            "kind": "language_bridge",
            "display_name": "C++ Bridge",
            "runtime_family": "bridge",
            "surface_runtimes": ["legacy_bridge", "shell"],
            "supported_human_languages": ["*"],
            "supported_target_technologies": ["cpp"],
            "translator_impl_language": "python",
            "delivery_languages": ["c++", "markdown"],
            "coupling_modes": ["embedded_target_code", "documentary_bridge"],
            "installation_mode": "manual_or_builtin",
            "source": {
                "type": "local_builtin",
                "locator": "src/usehbn/connectors/catalog.py",
                "trust_level": "approved",
            },
            "requires_human_approval": True,
        },
        {
            "connector_id": "hbn.connector.bridge.csharp",
            "kind": "language_bridge",
            "display_name": "C# Bridge",
            "runtime_family": "bridge",
            "surface_runtimes": ["legacy_bridge", "shell"],
            "supported_human_languages": ["*"],
            "supported_target_technologies": ["csharp"],
            "translator_impl_language": "python",
            "delivery_languages": ["csharp", "markdown"],
            "coupling_modes": ["embedded_target_code", "documentary_bridge"],
            "installation_mode": "manual_or_builtin",
            "source": {
                "type": "local_builtin",
                "locator": "src/usehbn/connectors/catalog.py",
                "trust_level": "approved",
            },
            "requires_human_approval": True,
        },
        {
            "connector_id": "hbn.connector.bridge.c",
            "kind": "language_bridge",
            "display_name": "C Bridge",
            "runtime_family": "bridge",
            "surface_runtimes": ["legacy_bridge", "shell"],
            "supported_human_languages": ["*"],
            "supported_target_technologies": ["c"],
            "translator_impl_language": "python",
            "delivery_languages": ["c", "markdown"],
            "coupling_modes": ["embedded_target_code", "documentary_bridge"],
            "installation_mode": "manual_or_builtin",
            "source": {
                "type": "local_builtin",
                "locator": "src/usehbn/connectors/catalog.py",
                "trust_level": "approved",
            },
            "requires_human_approval": True,
        },
    ]
